export const getRandomAPI = () => {
  const randomAPIs = [
    "Generate educational quizzes based on specific topics",
    "Create a plot for a role-playing game adventure based on theme, player level and setting",
    "Provide mental wellness exercises based on user mood",
    "Create personalized workout plans based on fitness goals and equipment",
    "Offer mock job interview questions tailored to specific industries",
    "Suggest creative writing prompts for different genres and themes",
    "Generate marketing content ideas for various business types and audiences",
    "Generate personalized travel itineraries based on destinations and interests",
    "Develop recipes based on dietary needs, themes, or available ingredients",
    "Generate movie plot ideas by different genres",
    "Suggest home decoration and design ideas based on personal style and space",
    "Provide personalized financial advice and investment strategies",
    "Generate theme and activity suggestions for special events",
    "Generate fake news articles",
    "Suggest book recommendations based on past reading history and preferences",
    "Offer personalized skincare and beauty routines based on skin type and concerns",
    "Generate unique gift ideas for special occasions based on recipient interests",
    "Suggest DIY project ideas based on skill level and available materials",
    "Generate coding challenges and exercises for various programming languages and skill levels",
    "Create custom meditation and yoga routines based on user experience and goals",
    "Offer plant care advice and gardening tips based on climate and space availability",
    "Generate music playlists based on mood, genre preference, or activity",
    "Develop personalized art and craft project ideas based on interests and skill levels",
    "Suggest weekend activity plans based on weather, location, and interests",
    "Provide pet care advice and tips based on the type of pet and specific needs",
    "Suggest personalized fashion styling tips based on individual style preferences and body type",
    "Create unique cocktail or beverage recipes based on available ingredients",
    "Generate custom photo album themes and layout ideas",
    "Provide historical facts and trivia based on specific eras or regions of interest",
    "Generate daily or weekly personal finance tips and budget management strategies",
    "Create a virtual tour itinerary of a historical site or museum based on user interests",
    "Create customized pet training routines for different pet species and behaviors",
    "Suggest hobby ideas and resources based on interests and available time",
    "Positive affirmation generator tailored to individual goals and challenges",
    "Generate custom joke ideas based on personal humor style",
    "Provide personalized poetry or songwriting prompts based on themes or emotions",
    "Suggest science experiment ideas for different age groups and skill levels",
    "Offer navigation and communication tips for international travel based on destination",
    "Offer custom bedtime stories for children based on their interests and age",
    "Suggest local cultural or artistic events based on interests and location",
    "Provide daily sustainability tips and eco-friendly lifestyle suggestions",
    "Generate character ideas and backstories for writers and role-playing gamers",
    "Offer advice on relationship and communication challenges",
    "Develop personalized strategies for stress relief and relaxation",
    "Generate personalized brain teasers and puzzles based on difficulty preference",
    "Suggest unique painting or drawing prompts for artists of varying skill levels",
    "Offer custom meal planning for special dietary needs, like low-carb or gluten-free diets",
    "Develop beginner-friendly programming project ideas in various languages",
    "Create personalized hydration and water intake plans based on lifestyle and health goals",
    "Suggest historical book or documentary recommendations based on specific interests or periods",
    "Offer custom gardening plans, including plant selection for different climates and spaces",
    "Generate daily or weekly self-care routines tailored to individual needs and schedules",
    "Provide recipe adaptations for allergy-friendly cooking",
    "Suggest local adventure sports or activities based on thrill level and physical ability",
    "Develop ideas for sustainable and eco-friendly travel",
    "Offer organization and productivity tips tailored to specific work or study environments",
    "Generate custom comic strip or cartoon ideas for amateur artists or hobbyists",
    "Suggest music pieces to learn for learning an instrumentbased on musical interests and skill level",
    "Provide home brewing or winemaking recipes and tips based on user experience and taste preference",
    "Generate lesson plan ideas for teachers based on grade, subject and theme",
    "Suggest full names for characters in movies, books or other stories",
    "Create random prompts for AI image generators",
    "Suggest activity ideas for bored kids",
    "Write satirical articles based on a theme",
    "Offer fashion suggestions and advice based on user needs",
    "Create RPG encounter scenarios based on theme and setting",
    "Generate themes and settings for fantasy game roleplaying adventures",
    "Suggest project ideas for an art student based on their medium and interests",
  ]
  return randomAPIs[Math.floor(Math.random() * randomAPIs.length)];
};
